version: '3.8'
services:
  stats-server:
    build: ./stats/stats-service
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=statsDbAdmin
      - SPRING_DATASOURCE_PASSWORD=stats-pass

  stats-db:
    image: postgres:15.0-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=statsDbAdmin
      - POSTGRES_PASSWORD=stats-pass

  ewm-service:
    build: ./ewm
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmDb
      - SPRING_DATASOURCE_USERNAME=ewmDbAdmin
      - SPRING_DATASOURCE_PASSWORD=ewm-pass
      - SERVICES_STATSERVICE_URI=http://stats-server:9090

  ewm-db:
    image: postgres:15.0-alpine
    container_name: ewm-db-container
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewmDb
      - POSTGRES_USER=ewmDbAdmin
      - POSTGRES_PASSWORD=ewm-pass
